### ISSUE TITLE
First version release

### ISSUE THREAD

**Issue by ferrucc-io** [juneHQ/houseplant#8]
- [x] #9
- [x] Dogfood and use within the core June codebase
- [x] #10
- [x] Find core things to improve before releasing
- [x] Announcement post why we built this: https://june.ghost.io/ghost/#/editor/post/674dd91959927c00019540ca
